### ISSUE TITLE
Ignoring projects and contexts

### ISSUE THREAD

**Issue by stsgit** [rkokkelk/todo.txt-ext#16]
Hi,

I like the idea of your addin.

But:
It ignores projects and contexts. Neither categories nor locations are used.

I just started from the scratch.
Thunderbird 45.5.1
Lightning 4.7.5.1
your ext 0.7.1

I started with empty files todo.txt and done.txt.

If I enter categories or location in Lightning they are just shortly displayed after saving the task. After sync they vanish.
If I enter a task directly in my todo.txt-file they projects and contexts are just displayed in the task's title but not in Thunderbird task's attributes.

![image](https://cloud.githubusercontent.com/assets/24506623/21080176/cf79f0a2-bfa8-11e6-846b-617476ac88ef.png)

Bye,
Stefan

**Comment by stsgit** [comment]
Hi,

I answered you via private mail 3 days ago.

Bye,
Stefan

**Comment by rkokkelk** [comment]
Hi Stefan,

Thank you, I've received the files. I'll schedule a development day soon and then I'll try to resolve the issue. Keep you posted.

**Comment by rkokkelk** [comment]
Hi Stefan,

My apologies I have not taken a close enough look at the screen shot at first. The third option, which is enabled in your case, ensures that the project and context (location and categories) are shown in the title instead of the location and categories within Thunderbird. The reason is that you see it briefly when entering it into Thunderbird because the add-on takes a couple of seconds to complete reload and show all the todo's in the tasks in the format as set by the options.

If you disable the third option you should be able to use the location and categories within Thunderbird. I therefore close this issue, if you have any further problems please feel free to reopen this issue.

**Comment by stsgit** [comment]
Hi,

ok! Thanks for your time. It wasn't clear to me that this means "only in title". It works now as expected. Great.

Bye,
Stefan

**Comment by rkokkelk** [comment]
Hi, 

No problem, it might be that the explanation of the option is not sufficient because I used to Google translate to translate the descriptions. So if you could provide a better translation so that future users would not make this error I would be very grateful.

Have a nice Christmas!

**Comment by stsgit** [comment]
Hi,

here are my suggestions:

1. "Thunderbird's Funktionalität nutzen"

2. "Erzeugungsdatum der Todo's nutzen"

3. "Projekte und Kontexte im Titel zeigen (statt in Kategorie und Ort)"

Maybe you can give short explanations directly on the settings page.


Would it be possible to offer 3 options for number 3 in a dropdown field?:

"Show projects and contexts in..."    (title, Thunderbird's properties, 
both)


Bye,
Stefan

Am 25.12.2016 um 12:56 schrieb Roy Kokkelkoren:
