### ISSUE TITLE
multiple instances appearing

### ISSUE THREAD

**Issue by pcause** [rkokkelk/todo.txt-ext#17]
I am using the nightly version of Thunderbird.  Each time I restart the app an extra todo.txt account appears so that I have multiple task lists for the same todo.txt file.

**Comment by rkokkelk** [comment]
Hi, 

Thank you for your feedback. This is indeed not the default behaviour. A single calendar should be generated if does not exists otherwise use the existing one. I'll verify the results on the nightly version of Thunderbird. 

Just a quick questions for verification if you uninstall the add-on is the Todo.txt calendar removed or not?

Thank you.

**Comment by rkokkelk** [comment]
Hi pcause,

I've tried to verify your bug but unfortunately I have not been able to reproduce it. I have been using Thunderbird `52.0a2 (2017-01-09)` but the add-on is functioning as expected.

You could you specify more specifically which version you are using and under what conditions. So that I can hopefully reproduce the issue.

**Comment by pcause** [comment]
It seems to be fine on newer nightly builds.  likely somehting broken in lightening or the gdata provider.
