### ISSUE TITLE
Error when marking a task as completed

### ISSUE THREAD

**Issue by JoergPalmer** [rkokkelk/todo.txt-ext#20]
The interaction with my todo.txt file works just fine, such as adding or deleting tasks.
However, when I'm ticking off a task as competed, the following happens:

1. Warning message: "oDoneStream is not defined"
2. Error message: "Error writing calendar <name>", MODIFICATION_FAILED

As a result, the task in question is deleted from the todo.txt file (which is correct). The done.txt file remains untouched, meaning the task is not added.

**Comment by rkokkelk** [comment]
Hi, 

My apologies for my late reply but could you provide me with some additional information so that I can tackle the issue. 

* Which version of the add-on and Thunderbird are you using? 
* Do you have any additional add-ons enabled? 
* Could you provide me with an example of your todo.txt & done.txt file?
* Did you specify the location of the done.txt file in the properties?

Thank you for reporting this issue.

**Comment by rkokkelk** [comment]
My  sincere apologies, I've made a small error within the code which resulted in the issue. A new version is uploaded to Mozilla and should be made available within the next few days which will resolve this issue. I will close this issue but if the fix was not sufficient or if there are other relevant issues please let me know.

Thank you for reporting this.

**Comment by JoergPalmer** [comment]
Thanks for taking care about this! Got the update and can confirm that the issue went away.

I have notice another glitch though, but guess it is better to open a new issue for that.
