### ISSUE TITLE
Do not display tasks in calendar view

### ISSUE THREAD

**Issue by knoddle** [rkokkelk/todo.txt-ext#23]
Firstly, excellent add-on!
Is it possible to have the Todo.txt Calendar enabled but not show tasks in the Calendar view? I have multiple calendars and Todo.txt entries overwhelm them. If I disable it in Calendar view it is also disabled in Task view. I know I can click to enable/disable depending upon which view is selected but it would be nice to be able to suppress the output in Calendar view as an option.

**Comment by JoergPalmer** [comment]
In the settings you can select (or rather not select) "Use Thunderbird functionality". Then no calendar view items are created. On the other hand the categories and locations are also not used.

I allow myself to chime in here. Maybe it would be possible to split the option setting in two pieces? One for the integration itself (creation date, due date, categories, locations) and another one to create / show calendar items. Speaking for myself, I would like to use the TB integration in general, but rather would like not to see calendar items.

**Comment by rkokkelk** [comment]
The fuctionality that you mention is not something that is decided by the add-on but is the default functionality of Thunderbird/Lightning itself. If within a task a due date or starting date is specified the task itself will be shown within the calendar.

As mentioned by @JoergPalmer, it is possible to prevent this by disabling the ' Use Thunderbrd fuctionality' option. However, it is also possible to prevent this behaviour if you disable the 'Use the Todo's creation timestamp' option which will prevent the use of the start date entry within the task resulting in no tasks being shown in the calendar.

So in general I do not think that this behaviour can be altered within my add-on because it performed by Thunderbird/Lightning itself. Maybe there exists an option within Thunderbird/Lightning to prevent this type of behaviour.

**Comment by JoergPalmer** [comment]
Fair enough ... Thank you for the clarification. For myself, I will skip the creation date to try this out. The creation date comes in very handy though to see for how long a task is sitting in the system.
