### ISSUE TITLE
Only Title, Priority and Dates are set

### ISSUE THREAD

**Issue by aetherfaerber** [rkokkelk/todo.txt-ext#26]
Hi,

I've given it multiply attempts, reinstalled the addon and reinitiated calendars, deleted and recreated the todo.txt file and replaced it with another sample file, but still the same:

Using the example line"(A) foobar +Dev +Home @PR" from the instructions priority is the only property which is displayed by Thunderbird/Lightning. Tags and location just remain in the title as they are but don't seem to be recognized by TB. When I set due/begin-dates in TB, only the days are synchronized to the todotxt-file but the exact time remains unknown.

Thunderbird 45.8.0
Lightning 4.7.8
todo.txt-ext 0.8.3

No related errors are reported in the error log

Thanks for looking into this.

**Comment by rkokkelk** [comment]
Hi, 

The Add-on contains several preferences which modifies the behavior of the add-on. One of which is used to specify whether the Categories and Projects are displayed only in the title or within the specified Thunderbird fields. So if you disable this option, the categories and location should be used in Thunderbird. Could you try this option and verify whether this suits your situation.

Secondly, it is correct that only the dates are used within the todo.txt and not the time. Because the todo.txt format only support dates and not times so that is why the time is not parsed in TB.

If you have any further questions, please let me know.

**Comment by aetherfaerber** [comment]
Oh yes, I see.
I had tried the "Thunderbird functionality" optio but somehow ignored the others because the descriptions (at least in German) didn't really make much sense. Submitted a somehow improved translation, although imho the options could be described more explicitly (e.g. stating that Categories and Projects will ONLY be displayed in theTitle).

Thanks a lot for your quick reply and for providing this great addon!

**Comment by rkokkelk** [comment]
Nop problem, thank you for the PR. 

If you have time to submit improved translations please feel free to do so. Otherwise I'll have to stick to Google Translate. 

Thank you again.

**Comment by rkokkelk** [comment]
Version `0.8.4` is now submitted to Mozilla which contains your improved translations. So it should be made available within the next couple of days. Also added your name to the Thanks section in the README.

Thank you again for your help.
