### ISSUE TITLE
Dropbox Permission denied when syncing todo.txt

### ISSUE THREAD

**Issue by renns** [rkokkelk/todo.txt-ext#29]
I currently use the SimpleTask app on my android phone to handle my todo.txt list. It syncs via dropbox. On my computer, I have Dropbox setup. So my todo.txt file always gets synced between my phone and my computer.

However, when I enable the todo.txt-ext in Thunderbird, Dropbox isn't able to sync my files due to the error "permission denied".

Reproduction steps:
- Install Dropbox on PC
- Create todo.txt / done.txt files in Dropbox folder on PC
- Get SimpleTask android app
- Connect SimpleTask to your Dropbox account and point to same todo.txt / done.txt files
- Create task using todo.txt-ext
- Verify that task shows up in SimpleTask
- Complete task using SimpleTask
- Look at Dropbox system tray icon on PC (hover mouse over it)
- Notice error message "Can't sync "todo.txt" (permission denied)"

**Comment by rkokkelk** [comment]
Hi, 

Thank you for reporting this issue and my apologies for my late reply I have been rather busy the last couple of days. But in order for me to resolve this issue could you give me some additional information.

Namely the initial information of the file before using my add-on, such as owner of file, creation timestamps,etc. And the resulting information of the file after you have used my add-on. So that I can verify what my add-on changes in your situation. 

Thank you!

**Comment by renns** [comment]
[ProcessMonitorOutput.zip](https://github.com/rkokkelk/todo.txt-ext/files/930324/ProcessMonitorOutput.zip)

Not quite what you asked for, but attached is the csv output from Sysinternals Process Monitor.

I did a capture of all events for that file for about 1.5 minutes. Take a look at the CreateFile and CloseFile operations. You'll notice that you hold the file open for a while after it is read. Also, I counted 8 CreateFiles and only 7 CloseFiles, which indicates to me that something is holding onto the file longer than it needs to.

**Comment by renns** [comment]
Just looking through your source code a bit, I noticed that you get the input stream for the todo and done txt files, but nothing ever explicitly closes the streams. I'm guessing that before Dropbox attempts to update changes, it makes sure there are no open handles to the file. Since your extension is not closing the streams, an open handle may exist on the file, causing Dropbox to fail.

**Comment by rkokkelk** [comment]
Hi, thanks for the elaborate reply. This definitely helps in pinpointing the issue. I'll look into closing the files properly. I myself do not use dropbox in the same configuration as you. Are you interested in testing the add-on when I push the fixes to a certain branch? 

Thanks again!

**Comment by renns** [comment]
Sure. I can take a look once you have a build with the fixes.

**Comment by manmatteo** [comment]
I have the same issue and I am also willing to help testing.

**Comment by rkokkelk** [comment]
Hi Guys,

My sincere apologies for the delay but I've finally rewritten the read file functionality so that it now uses the official modern Mozilla readFile function using Promises. The new version `0.8.5` has just been submitted to Mozilla and should be made available in the next couple of days.

I will close this issue, however, if some of you still encounter issues related to file locking, please feel free to reopen this issue.

Kind regards
