### ISSUE TITLE
on latest thunderbird nightly/lightning can't see todo's

### ISSUE THREAD

**Issue by pcause** [rkokkelk/todo.txt-ext#31]
I installed latest thunderbird nightly and i got an error message and my todo list was disbaled.  i uninstalled and reinstalled but now the todo list doesn't even show up.  on latest (July 5) thunderbird and matching gdata/lightning dailys.

**Comment by rkokkelk** [comment]
This issue has been fixed. There were some functions which were no longer available in Thunderbird 56.* so they had to be replaced. A new version of the add-on has been submitted for review `0.8.6` which will contain the fix. The add-on should be made available in the next couple of days.

I will close this issue, if you determine that your problem is not entirely fixed please feel free to reopen this issue.
