### ISSUE TITLE
Hide tasks in calendar

### ISSUE THREAD

**Issue by gsantner** [rkokkelk/todo.txt-ext#40]
Currently all tasks with some kind of date information are shown in the calendar, which pollutes the calendar with a lot of stuff which is mostly some todo for later. It would be great to have an general checkbox toggle to enable/disable showing in calendar view.

**Comment by rkokkelk** [comment]
It is by default that Todo's (Tasks as called in TB) with an Start and Due date will be shown in the calendar. Currently the add-on has the option do display the Todo's just as text or to format them according to a TB task. So I would advise to disable this options so that the todo's are just shown as text without any further formatting.

I you wish to have the option to use a TB task with start & due date without them being shown in the calendar I would advice to report this feature request to the Thunderbird developers themselves. Unfortunately I cannot enable this within the add-on.
