### ISSUE TITLE
Pre-requisites for todo.txt-ext ?

### ISSUE THREAD

**Issue by christophe-dupriez** [rkokkelk/todo.txt-ext#41]
Hi! I installed the extension, restarted Thunderbid, then configured the todo file path, restarted Thunderbird and nothing appears anywhere (but extension is active). Do I need to install Lightning or something else first? Why this is not documented ? THANKS FOR YOUR HELP ! (recent Linux Mint, Thunderbird 52.4.0 64 bits)

**Comment by rkokkelk** [comment]
Hi,

Lightning is indeed mandatory for the add-on and is thus stated as required on the add-on [webpage](https://addons.mozilla.org/nl/thunderbird/addon/todotxt-extension/). Furthermore it is mentioned in the description that Lightning is needed by the add-on. However, as you stated this might not be that apparent. 

For your situation, removing the add-on, installing Lightning and reinstalling the add-on should fix this issue. For you information and further use changing the settings of the add-on does not require a restart.

Because Lightning is currently installed by default for the more recent versions of Thunderbird I will not add any additional warnings for the requirement of the Lightning add-on.

I trust that hereby you issue is resolved and therefore this issue will be closed. However, if adding the Lightning add-on does not resolve this issue please feel free to reopen this issue.
