### ISSUE TITLE
Time integration

### ISSUE THREAD

**Issue by Lost-Projects** [rkokkelk/todo.txt-ext#45]
Having set up the add on, I don't seem to use time with due dates. Thunderbird allows a time to be set with dates, but upon synchronization, this reverts to 00:00. It can be a bit demoralising to start the day with a list of task that are already overdue - coloured red in Thunderbird's list. It would be nice to be able to order tasks by due time.

I have struggled to find any mention of time in the todo.txt documentation and I have not found a format that seems to work. If it is possible then, I guess this add on does not support it as setting the time in Thunderbird does not transfer to the todo.txt file and the setting in TB is lost on synchronization.

1. If use of time is possible, do you know where I might find documentation on this (or a simple one-line demonstration of the format would be great)?
2. If time is supported, then I guess this is a feature request for the add on to support it.

Thanks!

**Comment by rkokkelk** [comment]
Hi,

Thanks for the feedback. However, the add-on is mainly implemented to follow the  syntax of the todo.txt application which, as far as i know, does not support time. Therefore it is currently set the time to 00:00:00, however as I might presume from your comment this can also be set to the end of the day e.g. 23:59:59. 

I think time support will not be supported because although it might be used supported by TB it is not supported by todo.txt format. However, in your case might it be sufficient for the time to be set to the end of the day?

**Comment by Lost-Projects** [comment]
Thank you for your reply. I do not know where to set this default time. I noticed that 9 months ago, you fixed a bug with time in modules. I looked at todoclient.jsm and line 64 seems to set hours to zero. Should I alter that line (I'll have to find where the addon is installed!)? If you are offering to set 23:59 as the default, then that would be great.

I see a reference to this issue is listed in this timeline. I went to the original project and see that someone has proposed a time format about a month ago. I agreed with the proposal and suggested that the main project approve proposed format extensions so that the text can remain interoperable across apps. If they were to do that then if anyone wanted to extend the format, they could either check for a standard notation or ask for their solution to be approved. If in the future you decided to support time in the due date, you could check how the text file would format time.

I have also seen the issue about updating the code for version 60 of TB, so I understand that any changes may be several months away, but fortunately, I'm still on version 52.9.1!

**Comment by rkokkelk** [comment]
I've just changed the default time to the end of day. Therefore the issue you mentioned should not happen any more. If the functionality does not work as expected, please feel free to reopen this issue.

If you find any new information of a time format which is sued by the core todo.txt application, please let me know cause I'll update the add-on accordingly.

**Comment by a-e-e-m** [comment]
In my understanding, todo.txt is rather a set of formatting rules together with a command line tool implementing these rather than an application (on top of which many applications are built, indeed). I think that even the format <due:YYYY-MM-DD> isn't part of the rules implemented in the command line tool. In any case, I think there is nothing against adding a due time functionality, and maybe a starting time functionality, too. I would love it! Of course, it may be that other applications use the <due:YYYY-MM-DD> format and that adding time would screw up things for people using todo.txt-ext and this other application. Maybe you could implement something like <start:YYYY-MM-DDTHH:MM> and <end:YYYY-MM-DDTHH:MM> to define starting time and end time of a task which would be seen just as part of the task text by other applications?
