### ISSUE TITLE
Thunderbird 68.* compatibility?

### ISSUE THREAD

**Issue by lucker999** [rkokkelk/todo.txt-ext#63]
Soon we all have to live with the new major Thunderbird upgrade (release 68). The thing with this update is that add-ons may only work if the add-on developers have adapted them. Any add-on that has not been adapted will be disabled when you run Thunderbird 68.*

So, I definitely would really appreciate to continue using this awesome addon. Could you please look into the issue and ensure that we will not be sidelined?

Thanks in advance!

**Comment by rkokkelk** [comment]
Hi, thank you for your support. 

I'm definitely looking into the fact of making this add-on available for TBv60. However, a quick look into making this add-on available requires more rewrite than I initially thought. Especially the settings interface has to be redone completely. So although I'm looking into it, please know that it might take some time before I can make it completely compatible. 

My progress on the rewrite can be seen in branch: [tbv68](https://github.com/rkokkelk/todo.txt-ext/tree/tb_v68)

**Comment by phocean** [comment]
Thank you. I am going to test it if it is usable.

**Comment by rkokkelk** [comment]
I've rewritten the add-on so that it supports Thunderbird version 68 and up. I've just uploaded the new version to Mozilla so it should be made available in the next couple of days. I therefore close this issue, if any new issues arise with this new version please let me know by reopening this issue and mentioning the bugs.

If you can't wait for Mozilla to review the new version, feel free to build the add-on from source code. Instructions to do this are now available in the [Readme](https://github.com/rkokkelk/todo.txt-ext#building).

**Comment by phocean** [comment]
Wow, thanks a lot @rkokkelk !!
You have been very fast and it's working perfectly !

Your extension is very useful and is an important part of my workflow, thus of my productivity.

Again, many thanks!

**Comment by lucker999** [comment]
What about Windows? Please, we still use this OS...

**Comment by rkokkelk** [comment]
The addon does not contain specific functions for a specific os. So although I published the build steps for Linux does not mean that the resulting zip file does not run on other oses. Even cloning this repo and zipping it, renaming it to a xpi file is enough to get the add on installed in TB on windows and Mac.

The reason that windows did not receive an update yet is because the thunderbird team took a long time time reviewing the add-on. But I just received notification that the new version is online, so any add-on current installed on either Linux, windows of Mac should be automatically updated and thus include the TB 68+ functionality.

If the new addon does not work properly, please feel free to reopen this issue.
